#!/usr/bin/env python3
"""Derive the UO network-compression code table from the vendored ModernUO source.

The server Huffman-compresses everything it sends after game login, so the client
needs the same code book to read it.  Rather than transcribing the table by hand
(257 entries, one typo = a silently corrupt stream), we parse it out of the
server implementation we already vendor and emit a Python module.

    python3 tools/gen_huffman.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "reference/modern_uo/Projects/Server/Network/NetworkCompression.cs"
OUT = ROOT / "anacrom/protocol/_codebook.py"


def main() -> int:
    if not SRC.exists():
        print(f"missing protocol oracle: {SRC}", file=sys.stderr)
        return 1

    text = SRC.read_text(encoding="utf-8", errors="replace")
    block = re.search(r"ReadOnlySpan<int>\s+rawTable\s*=\s*\[(.*?)\]\s*;", text, re.S)
    if not block:
        print("could not locate rawTable literal", file=sys.stderr)
        return 1

    nums = [int(tok, 16) for tok in re.findall(r"0x[0-9A-Fa-f]+", block.group(1))]
    if len(nums) != 257 * 2:
        print(f"expected 514 values, parsed {len(nums)}", file=sys.stderr)
        return 1

    pairs = [(nums[i * 2], nums[i * 2 + 1]) for i in range(257)]

    # Sanity: a prefix code must have no symbol that is a prefix of another.
    seen = {}
    for sym, (length, code) in enumerate(pairs):
        for upto in range(1, length):
            if (upto, code >> (length - upto)) in seen:
                print(f"symbol {sym} collides with a shorter code", file=sys.stderr)
                return 1
        seen[(length, code)] = sym

    lines = [
        '"""Generated by tools/gen_huffman.py -- do not edit."""',
        "",
        "# (bit length, code) indexed by symbol; index 256 is the end-of-block marker.",
        "CODEBOOK = [",
    ]
    for i in range(0, 257, 8):
        chunk = ", ".join(f"({l}, 0x{c:03X})" for l, c in pairs[i:i + 8])
        lines.append(f"    {chunk},")
    lines.append("]")
    lines.append("")
    lines.append("TERMINATOR = 256")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(pairs)} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
